plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - README.md
  - PC Assemble (Lab)/Reflection.md
  - Industrial Talk (Assignment 1)/IndustrialTalkReflection.md
  - Design Thinking Project/DesignThinkingReportReflection.md

include_relative:
 - PC Assemble (Lab)/Reflection.md
