# Site settings
title: e-Portfolio
email: barriejaffery@graduate.utm.my
description: > # this means to ignore newlines until "baseurl:"
  testing.
baseurl: "/UTM-e-Portfolio" # the subpath of your site, e.g. /blog/
url: "https://dotrovi.github.io" # the base hostname & protocol for your site
github_username:  dotrovi

# Build settings
markdown: kramdown
permalink: /:year/:title:output_ext

plugins:
  - jekyll-relative-links

relative_links:
  enabled: true
  collections: true

include:
  - README.md
  - PC Assemble (Lab)
  - Industrial Talk (Assignment 1)
  - Design Thinking Project
